<?php
/**
 * \controller Testing
 */
class TestingAbstractor extends SpiritAbstractor implements StaticBound, MemoryXDO, ControllerFeeded, SessionedSpirit{
	/**
	 * Method Generated by Bong Admin panel
	 */			
	public function main(){
		/*TODO Not Implemented Yet*/
	}
}
?>
