<?php
/**
 * \controller default
 */
class defaultController extends BongAppController {

	/**
	 * Method Generated by Bong Admin panel
	 */			
	public function main(){
		/*TODO Not Implemented Yet*/
	}	/**
	 * Method Generated by Bong Admin panel
	 */			
	public function say($name="Null"){
		$this->data->name = $name;
	}
}