<?php
/**
 * \controller default
 */
class defaultController extends BongAppController {

	/**
	 * Method Generated by Bong Admin panel
	 */			
	public function main(){
		/*TODO Not Implemented Yet*/
		$this->data->name = "Neel Basu";
	}
}
